#version: '3.1'
#
#services:
#  pg_db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD='root'
#      - POSTGRES_USER='root'
#      - POSTGRES_DB='django_currency'
#      - PGDATA="/var/lib/postgresql/data/pgdata"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#    ports:
#      - ${POSTGRES_PORT:-5432}:5432

version: '3'
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pgData:/var/lib/psotgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: django_currency