# Generated by Django 3.2.9 on 2021-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Курс к рублю'),
        ),
    ]
